name: Refresh Pulumi State

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm refresh operation'
        required: true
        default: "no"

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    if: github.event.inputs.confirm == 'yes'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pulumi pulumi-aws boto3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: PulumiRefresh

      - name: Refresh Pulumi Stack
        uses: pulumi/actions@v4
        with:
          command: refresh
          stack-name: dev
          work-dir: .
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
